[tlv-beach-gordon]
name = "Tel Aviv Gordon Beach"
url = "https://edge01.balticlivecam.com/blc/Israel1/index.m3u8"

  [[tlv-beach-gordon.query]]
  name = "token"
  url = "https://balticlivecam.com/wp-admin/admin-ajax.php?action=auth_token&id=4487"
  regex = "token=([^']+)"

[herzeliya-marina-south]
name = "Herzeliya Marina South"
url = "http://62.219.45.26:120/mjpg/video.mjpg"

[herzeliya-marina-north]
name = "Herzeliya Marina North"
url = "http://62.219.45.26:130/mjpg/video.mjpg"

[herzeliya-marina-main]
name = "Herzeliya Marina Main"
url = "http://62.219.45.26:140/mjpg/video.mjpg"

[tlv-muni-gordon]
name = "Tel Aviv Muni Gordon"
url = "https://cdn.mainstreaming.tv/live/101468/VflFjv8/playlist.m3u8"

[tlv-muni-shoreline]
name = "Tel Aviv Muni Shoreline"
url = "https://cdn.mainstreaming.tv/live/324179/EkZ5WSw/playlist.m3u8"

[tlv-muni-dolphinarium]
name = "Tel Aviv Muni Dolphinarium"
url = "https://cdn.mainstreaming.tv/live/324225/8KyLdCd/playlist.m3u8"

[tlv-muni-jaffa]
name = "Tel Aviv Muni Jaffa"
url = "https://cdn.mainstreaming.tv/live/324224/xhyk08w/playlist.m3u8"
