[evlaim]
url = "https://5d8c50e7b358f.streamlock.net/live/EVLAIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[olga]
url = "https://5d8c50e7b358f.streamlock.net/live/OLGA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[ofakim]
url = "https://5d8c50e7b358f.streamlock.net/live/OFAKIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[orakivakvish2]
url = "https://5d8c50e7b358f.streamlock.net/live/ORAKIVAKVISH2.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[orakivakvish4]
url = "https://5d8c50e7b358f.streamlock.net/live/ORAKIVAKVISH4.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[macker]
url = "https://5d8c50e7b358f.streamlock.net/live/MACKER.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[elishema]
url = "https://5d8c50e7b358f.streamlock.net/live/ELISHEMA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[emunim]
url = "https://5d8c50e7b358f.streamlock.net/live/EMUNIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[eshelhanasi]
url = "https://5d8c50e7b358f.streamlock.net/live/ESHELHANASI.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[bethagedi]
url = "https://5d8c50e7b358f.streamlock.net/live/BETHAGEDI.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[beitrimon]
url = "https://5d8c50e7b358f.streamlock.net/live/BEITRIMON.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[gvulut]
url = "https://5d8c50e7b358f.streamlock.net/live/GVULUT.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[givatshmuel]
url = "https://5d8c50e7b358f.streamlock.net/live/GIVATSHMUEL.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[givati]
url = "https://5d8c50e7b358f.streamlock.net/live/GIVATI.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[gedera]
url = "https://5d8c50e7b358f.streamlock.net/live/GEDERA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[geha]
url = "https://5d8c50e7b358f.streamlock.net/live/GEHA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[golani]
url = "https://5d8c50e7b358f.streamlock.net/live/GOLANI.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[goral]
url = "https://5d8c50e7b358f.streamlock.net/live/GORAL.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[gilolong]
url = "https://5d8c50e7b358f.streamlock.net/live/GILOLONG.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[gilat]
url = "https://5d8c50e7b358f.streamlock.net/live/GILAT.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[gimzo]
url = "https://5d8c50e7b358f.streamlock.net/live/GIMZO.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[ginaton]
url = "https://5d8c50e7b358f.streamlock.net/live/GINATON.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[gilam]
url = "https://5d8c50e7b358f.streamlock.net/live/GILAM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[gandarom]
url = "https://5d8c50e7b358f.streamlock.net/live/GANDAROM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[ganyavne]
url = "https://5d8c50e7b358f.streamlock.net/live/GANYAVNE.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[ganot]
url = "https://5d8c50e7b358f.streamlock.net/live/GANOT.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[jiser]
url = "https://5d8c50e7b358f.streamlock.net/live/JISER.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[gesherhashalom]
url = "https://5d8c50e7b358f.streamlock.net/live/GESHERHASHALOM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[davrat]
url = "https://5d8c50e7b358f.streamlock.net/live/DAVRAT.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[dganyaroad57]
url = "https://5d8c50e7b358f.streamlock.net/live/DGANYAROAD57.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[dimona]
url = "https://5d8c50e7b358f.streamlock.net/live/DIMONA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hadasim]
url = "https://5d8c50e7b358f.streamlock.net/live/HADASIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hadarim]
url = "https://5d8c50e7b358f.streamlock.net/live/HADARIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hakfarhayarok]
url = "https://5d8c50e7b358f.streamlock.net/live/HAKFARHAYAROK.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hamovil]
url = "https://5d8c50e7b358f.streamlock.net/live/HAMOVIL.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hamahtesh]
url = "https://5d8c50e7b358f.streamlock.net/live/HAMAHTESH.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hamelaha]
url = "https://5d8c50e7b358f.streamlock.net/live/HAMELAHA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hasira]
url = "https://5d8c50e7b358f.streamlock.net/live/HASIRA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hasargel]
url = "https://5d8c50e7b358f.streamlock.net/live/HASARGEL.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[haogen]
url = "https://5d8c50e7b358f.streamlock.net/live/HAOGEN.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hakerach]
url = "https://5d8c50e7b358f.streamlock.net/live/HAKERACH.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hartuva]
url = "https://5d8c50e7b358f.streamlock.net/live/HARTUVA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hartuvb]
url = "https://5d8c50e7b358f.streamlock.net/live/HARTUVB.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hertzeliaeastroad531]
url = "https://5d8c50e7b358f.streamlock.net/live/HERTZELIAEASTROAD531.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hashiva]
url = "https://5d8c50e7b358f.streamlock.net/live/HASHIVA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hashomrim]
url = "https://5d8c50e7b358f.streamlock.net/live/HASHOMRIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hatishbi]
url = "https://5d8c50e7b358f.streamlock.net/live/HATISHBI.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[zvulun]
url = "https://5d8c50e7b358f.streamlock.net/live/ZVULUN.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[zihronyaakovkvish2]
url = "https://5d8c50e7b358f.streamlock.net/live/ZIHRONYAAKOVKVISH2.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[zichronyaakov]
url = "https://5d8c50e7b358f.streamlock.net/live/ZICHRONYAAKOV.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[havatshaarhagy]
url = "https://5d8c50e7b358f.streamlock.net/live/HAVATSHAARHAGY.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hativa7]
url = "https://5d8c50e7b358f.streamlock.net/live/HATIVA7.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hamed]
url = "https://5d8c50e7b358f.streamlock.net/live/HAMED.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[henroad531]
url = "https://5d8c50e7b358f.streamlock.net/live/HENROAD531.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hefer]
url = "https://5d8c50e7b358f.streamlock.net/live/HEFER.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[hatzav]
url = "https://5d8c50e7b358f.streamlock.net/live/HATZAV.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[tayasim]
url = "https://5d8c50e7b358f.streamlock.net/live/TAYASIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[yagur]
url = "https://5d8c50e7b358f.streamlock.net/live/YAGUR.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[yagel]
url = "https://5d8c50e7b358f.streamlock.net/live/YAGEL.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[yokneamilit]
url = "https://5d8c50e7b358f.streamlock.net/live/YOKNEAMILIT.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[yishai]
url = "https://5d8c50e7b358f.streamlock.net/live/YISHAI.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[karem]
url = "https://5d8c50e7b358f.streamlock.net/live/KAREM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[sataf]
url = "https://5d8c50e7b358f.streamlock.net/live/SATAF.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[kfarbaruch]
url = "https://5d8c50e7b358f.streamlock.net/live/KFARBARUCH.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[kfarhanasi]
url = "https://5d8c50e7b358f.streamlock.net/live/KFARHANASI.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[kfarwarburg]
url = "https://5d8c50e7b358f.streamlock.net/live/KFARWARBURG.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[kfarnahum]
url = "https://5d8c50e7b358f.streamlock.net/live/KFARNAHUM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[kareynaamannorth]
url = "https://5d8c50e7b358f.streamlock.net/live/KAREYNAAMANNORTH.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[karmieleast]
url = "https://5d8c50e7b358f.streamlock.net/live/KARMIELEAST.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[lahavkvish6]
url = "https://5d8c50e7b358f.streamlock.net/live/LAHAVKVISH6.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[lehavim]
url = "https://5d8c50e7b358f.streamlock.net/live/LEHAVIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[lod]
url = "https://5d8c50e7b358f.streamlock.net/live/LOD.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[latrun]
url = "https://5d8c50e7b358f.streamlock.net/live/LATRUN.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[mevomodiim]
url = "https://5d8c50e7b358f.streamlock.net/live/MEVOMODIIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[megido]
url = "https://5d8c50e7b358f.streamlock.net/live/MEGIDO.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[morasha]
url = "https://5d8c50e7b358f.streamlock.net/live/MORASHA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[mazkretbatya]
url = "https://5d8c50e7b358f.streamlock.net/live/MAZKRETBATYA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[mahaneofer]
url = "https://5d8c50e7b358f.streamlock.net/live/MAHANEOFER.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[mahaneamos]
url = "https://5d8c50e7b358f.streamlock.net/live/MAHANEAMOS.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[meiami]
url = "https://5d8c50e7b358f.streamlock.net/live/MEIAMI.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[mishoradumim]
url = "https://5d8c50e7b358f.streamlock.net/live/MISHORADUMIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[macabimreut]
url = "https://5d8c50e7b358f.streamlock.net/live/MACABIMREUT.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[malal]
url = "https://5d8c50e7b358f.streamlock.net/live/MALAL.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[maon]
url = "https://5d8c50e7b358f.streamlock.net/live/MAON.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[meona]
url = "https://5d8c50e7b358f.streamlock.net/live/MEONA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[mitzpemodiin]
url = "https://5d8c50e7b358f.streamlock.net/live/MITZPEMODIIN.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[mitkanadam]
url = "https://5d8c50e7b358f.streamlock.net/live/MITKANADAM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[nablat]
url = "https://5d8c50e7b358f.streamlock.net/live/NABLAT.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[nahalal]
url = "https://5d8c50e7b358f.streamlock.net/live/NAHALAL.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[neveilan]
url = "https://5d8c50e7b358f.streamlock.net/live/NEVEILAN.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[nofhagalilgovermentcenter]
url = "https://5d8c50e7b358f.streamlock.net/live/NOFHAGALILGOVERMENTCENTER.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[nahalhaelaroad6]
url = "https://5d8c50e7b358f.streamlock.net/live/NAHALHAELAROAD6.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[nahalhadera]
url = "https://5d8c50e7b358f.streamlock.net/live/NAHALHADERA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[nahalshalvaroad6]
url = "https://5d8c50e7b358f.streamlock.net/live/NAHALSHALVAROAD6.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[nahala]
url = "https://5d8c50e7b358f.streamlock.net/live/NAHALA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[nahshon]
url = "https://5d8c50e7b358f.streamlock.net/live/NAHSHON.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[nitzaneyoz]
url = "https://5d8c50e7b358f.streamlock.net/live/NITZANEYOZ.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[nirtzvi]
url = "https://5d8c50e7b358f.streamlock.net/live/NIRTZVI.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[neora]
url = "https://5d8c50e7b358f.streamlock.net/live/NEORA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[omer]
url = "https://5d8c50e7b358f.streamlock.net/live/OMER.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[okefrehovot]
url = "https://5d8c50e7b358f.streamlock.net/live/OKEFREHOVOT.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[einhamifrtz]
url = "https://5d8c50e7b358f.streamlock.net/live/EINHAMIFRTZ.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[eron]
url = "https://5d8c50e7b358f.streamlock.net/live/ERON.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[parkcaesarea]
url = "https://5d8c50e7b358f.streamlock.net/live/PARKCAESAREA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[parkbarlev]
url = "https://5d8c50e7b358f.streamlock.net/live/PARKBARLEV.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[poleg]
url = "https://5d8c50e7b358f.streamlock.net/live/POLEG.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[faradis]
url = "https://5d8c50e7b358f.streamlock.net/live/FARADIS.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[plugot]
url = "https://5d8c50e7b358f.streamlock.net/live/PLUGOT.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[komemiut]
url = "https://5d8c50e7b358f.streamlock.net/live/KOMEMIUT.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[kastina]
url = "https://5d8c50e7b358f.streamlock.net/live/KASTINA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[kiryatgatroad40]
url = "https://5d8c50e7b358f.streamlock.net/live/KIRYATGATROAD40.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[kiryatgatroad6]
url = "https://5d8c50e7b358f.streamlock.net/live/KIRYATGATROAD6.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[kiryattivon]
url = "https://5d8c50e7b358f.streamlock.net/live/KIRYATTIVON.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[roshhaaineast]
url = "https://5d8c50e7b358f.streamlock.net/live/ROSHHAAINEAST.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[roshhaayintrain]
url = "https://5d8c50e7b358f.streamlock.net/live/ROSHHAAYINTRAIN.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[rishonlezion]
url = "https://5d8c50e7b358f.streamlock.net/live/RISHONLEZION.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[ramot]
url = "https://5d8c50e7b358f.streamlock.net/live/RAMOT.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[raananacenter]
url = "https://5d8c50e7b358f.streamlock.net/live/RAANANACENTER.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[raanananorth]
url = "https://5d8c50e7b358f.streamlock.net/live/RAANANANORTH.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[sorek]
url = "https://5d8c50e7b358f.streamlock.net/live/SOREK.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[shores]
url = "https://5d8c50e7b358f.streamlock.net/live/SHORES.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[shilat]
url = "https://5d8c50e7b358f.streamlock.net/live/SHILAT.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[shaalabim]
url = "https://5d8c50e7b358f.streamlock.net/live/SHAALABIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[shaarhagai]
url = "https://5d8c50e7b358f.streamlock.net/live/SHAARHAGAI.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[shapirim]
url = "https://5d8c50e7b358f.streamlock.net/live/SHAPIRIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[telyosef]
url = "https://5d8c50e7b358f.streamlock.net/live/TELYOSEF.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[telmond]
url = "https://5d8c50e7b358f.streamlock.net/live/TELMOND.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[teladashim]
url = "https://5d8c50e7b358f.streamlock.net/live/TELADASHIM.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[tefen]
url = "https://5d8c50e7b358f.streamlock.net/live/TEFEN.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

[tikva]
url = "https://5d8c50e7b358f.streamlock.net/live/TIKVA.stream/playlist.m3u8"
tags = ["roadcams", "israel", "iroads"]

