[kan11]
name = "Kan Channel 11"
url = "https://kanlivep2event-i.akamaihd.net/hls/live/747610-b/747610/source1_2.5k/chunklist.m3u8"

[kan-hinuhit]
name = "Kan Hinuhit"
url = "https://kanlivep2event-i.akamaihd.net/hls/live/747600/747600/master.m3u8"

[reshet]
name = "Reshet Channel 13"
url = "https://reshet-live-il.ctedgecdn.net/13tv-desktop/r13.m3u8"

[keshet]
name = "Keshet Channel 12"
url = "https://keshethlslive-i.akamaihd.net/hls/live/512033/CH2LIVE_HIGH/index.m3u8"

    [[keshet.query]]
    name = "hdnea"
    url = "https://mass.mako.co.il/ClicksStatistics/entitlementsServicesV2.jsp?et=ngt&lp=/hls/live/512033/CH2LIVE_HIGH/index.m3u8&rv=AKAMAI"
    regex = 'hdnea=([^"]*)'
    # json = 'tickets.0.ticket' # json includes redundant "hdnea=" prefix

[arutz24]
name = "Keshet Channel 24"
url = "https://keshethlslive-lh.akamaihd.net/i/24live_1@195271/master.m3u8"

    [[arutz24.query]]
    name = "hdnea"
    url = "https://mass.mako.co.il/ClicksStatistics/entitlementsServicesV2.jsp?et=ngt&lp=/i/24live_1@195271/master.m3u8&rv=AKAMAI"
    regex = 'hdnea=([^"]*)'
    # json = 'tickets.0.ticket'

[knesset]
name = "Knesset Channel 99"
url = "https://w1.013.gostreaming.tv/Knesset/myStream/playlist.m3u8"

[shoppingil21]
name = "Shopping TV Israel Channel 21"
url = "https://shoppingil-metadata-rr-d.vidnt.com/live/shoppingil/ShoppingIL21TV/hls/metadata.xml"
smil = true
