[kan11]
name = "Kan Channel 11"
url = "https://kanlivep2event-i.akamaihd.net/hls/live/747610/747610/master.m3u8"

[kan-hinuhit]
name = "Kan Hinuhit"
url = "https://kanlivep2event-i.akamaihd.net/hls/live/747600/747600/master.m3u8"

[reshet]
name = "Reshet Channel 13"
url = "https://besttv1.aoslive.it.best-tv.com/reshet/studio/index.m3u8"
http_headers = ["Referer: https://besttv1.aoslive.it.best-tv.com/"]

[keshet]
name = "Keshet Channel 12"
url = "https://keshethlslive-i.akamaihd.net/hls/live/512033/CH2LIVE_HIGH/index.m3u8"

    [[keshet.query]]
    name = "hdnea"
    url = "https://mass.mako.co.il/ClicksStatistics/entitlementsServicesV2.jsp?et=ngt&lp=/hls/live/512033/CH2LIVE_HIGH/index.m3u8&rv=AKAMAI"
    regex = 'hdnea=([^\"]*)'
    json = 'tickets.0.ticket'

[knesset]
name = "Knesset Channel 99"
url = "https://w1.013.gostreaming.tv/Knesset/myStream/playlist.m3u8"
